### ISSUE TITLE
Project Peer Review Issues and Content Recommendations

### ISSUE THREAD

**Issue by dkovalenko420** [Ryanoakes1/WebTechProject#8]
Issues:
1. The Sitemap looks a little janky because the links are uncentred. To find this, you could change the CSS of **.centerize{}** to 
**margin-left: auto;
margin-right: auto;**

2. I did not realize there is a poll at the bottom of drinks.html, some visitors may miss it completely. This is why I would put the **form** above the **table**

Content:
1. I would recommend adding more pictures of the Woodquay Hostel at recommendations.html. The video is a little shaky and it isn't easy to understand whether the hotel is good.

3. I would also add more content to about.html because currently, it is a little short. You could talk about the activities you did, the people you met, the museums you visited, etc.

**Comment by Ryanoakes1** [comment]
Thank you for the bunch of really good ideas you presented. I took into consideration a lot of these ideas in my final version.
